### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Maxim-Filimonov** [cedricss/elm-batteries#1]
Just tried to create a demo using `yarn create`
And got this after running `yarn dev`
<img width="853" alt="Screen Shot 2019-08-01 at 17 39 13" src="https://user-images.githubusercontent.com/360645/62302586-49009080-b483-11e9-832b-623a5dc1d8d6.png">
Debug log:
```
▾_package = Failure BadBody …
0 = "Problem with the given value:\n\n\"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n <head>\\n <title>Elm Batteries Included!</title>\\n <meta name=\\\"viewport\\\" content=\\\"width=device-width\\\">\\n <meta name=\\\"description\\\" content=\\\"Elm + parcel + tailwind + cypress + netlify and more!\\\">\\n <meta property=\\\"og:url\\\" content=\\\"https://github.com/cedricss/elm-batteries\\\">\\n <meta property=\\\"og:title\\\" content=\\\"Elm Batteries Included!\\\">\\n <meta property=\\\"og:type\\\" content=\\\"article\\\">\\n <meta property=\\\"og:description\\\" content=\\\"Elm + parcel + tailwind + cypress + netlify and more!\\\">\\n <meta property=\\\"og:image\\\" content=\\\"/content_preview.e73c0f9e.jpg\\\">\\n <meta property=\\\"og:site_name\\\" content=\\\"Elm Batteries Included!\\\">\\n <meta name=\\\"twitter:card\\\" content=\\\"summary_large_image\\\">\\n <meta name=\\\"twitter:site\\\" content=\\\"@CedricSoulas\\\">\\n <meta name=\\\"twitter:creator\\\" content=\\\"@CedricSoulas\\\">\\n <meta name=\\\"twitter:image:alt\\\" content=\\\"Elm Batteries demo page\\\">\\n <script async=\\\"\\\" src=\\\"/elm-batteries-test.e31bb0bc.js\\\"></script>\\n <link rel=\\\"stylesheet\\\" href=\\\"/elm-batteries-test.e31bb0bc.css\\\"></head>\\n <body></body>\\n</html>\\n\"\n\nThis is not valid JSON! JSON Parse error: Unrecognized token '<'"
key = <internals>
route = ApiDemo
}
```
I get 304 in browser network requests for `http://localhost:1234/.netlify/functions/demo`

**Comment by cedricss** [comment]
Thanks! Here is a checklist that may help understanding the issue:

### Serverless functions checklist

- [ ] is the browser opened on http://localhost:8888/demo? (`8888` port)

![Netlify Dev on top of Parcel and serverless functions](https://concat.dev/netlify-dev.png)

- [ ] after `yarn dev`, is the message `Server now ready on http://localhost:8888` displayed?

<img width="424" alt="image" src="https://user-images.githubusercontent.com/802010/62313745-c3d0a800-b491-11e9-89dd-0effdba0d549.png">

- [ ] does the package.json `dev` script looks like this: https://github.com/cedricss/elm-batteries/blob/master/package.json#L21

- [ ] when initializing the project with `yarn create elm-batteries ./my-elm-app`, are the answers `yes` to `Dev platform and deployment with Netlify?` and `Serverless functions?`

<img width="438px" src="https://concat.dev/create-elm-batteries.png" alt="create-elm-batteries cli generator" />

Note: for reference, serverless functions are enabled in the [elm-batteries](https://github.com/cedricss/elm-batteries) Github template

**Comment by Maxim-Filimonov** [comment]
Hm.. Not sure what was the problem I have tried again now and it works... 
Haven't changed anything, magic 💥
